---

name: NewContainInstan

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]

env:
  #Azure Variables
  CONTAINER_NAME: containerdejohn
  RESOURCE_GROUP: Grupito
  IMAGE_PULL_SECRET_NAME: "your-image-pull-secret-name"
  #Docker Variables
  DockerImag: "johnmayorga18/hellohtml:ultimaversion"

jobs:
  build:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
    # Checks out the repository this file is in
    - uses: actions/checkout@v3
    
    #Inicializando
    - name: Loading
      run: cat sucess.txt
    
    # Intento iniciar sesion en el portal de azure
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Creo Un nuevo resource group
    - name: CrearGrupoRecursos
      run: |
        az group create \
        --location westus \
        --name $RANDOM \
        --tags Organización=SENA Lenguaje=HTML Plataforma=Docker

    # Intento Crear la instracia de Docker
    - name: CrearContainer
      run: |
        az container create \
        --resource-group 10755 \
        --cpu 1 \
        --memory 1.5 \
        --os-type Linux \
        --ip-address public \
        --ports 80 \
        --protocol tcp \
        --dns-name-label miconyainerp \
        --location westus \
        --name $CONTAINER_NAME \
        --image $DockerImag \
        --restart-policy OnFailure 
      id: get-acr-creds

...
